name: "VPN-FAIL!"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */1 * * *'
    
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  vpn-fail:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          
      - name: Execute PHP script
        run: |
          php index.php
          
      - name: Configure Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          git config credential.helper store
          
      - name: Commit changes
        run: |
          git add -A .
          git commit -m "üêà Last Run - $(TZ='Asia/Tehran' date '+%Y-%m-%d %H:%M:%S')"
          git push
          
